name: Test Bunicorn and Deploy Docs Site

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2

      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ matrix.bun }}-bun-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.bun }}-bun-

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun run test

      - name: Check for docs changes
        id: docs-changed
        run: |
          git diff --quiet HEAD^ HEAD docs/ && echo "changed=false" >> $GITHUB_OUTPUT || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Cache VitePress build
        id: cache-vitepress
        uses: actions/cache@v4
        with:
          path: docs/.vitepress/dist
          key: ${{ runner.os }}-vitepress-${{ hashFiles('docs/**') }}
          restore-keys: |
            ${{ runner.os }}-vitepress-

      - name: Build with VitePress
        if: steps.docs-changed.outputs.changed == 'true' || steps.cache-vitepress.outputs.cache-hit != 'true'
        run: |
          bun run docs:build
          touch docs/.vitepress/dist/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/.vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build-and-test
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2